### ISSUE TITLE
Redmine 1.1.x compatibility?

### ISSUE THREAD

**Issue by ghost** [Pertimm/redmine_extended_spent_time#2]
Are there any plans for this plugin to be compatible with Redmine v1.1.x?

It seems to install fine, but the delete time entry icon doesn't work properly and instead redirects users to a blank screen.

**Comment by jmvallet** [comment]
Commit 2b52b763271603e0263d must fix issues related to Redmine v1.1.x.

**Comment by ghost** [comment]
I've just tested this on Redmine v1.1.3 and it works fine. Thank you.

Any ideas if this will also be compatible with the upcoming v1.2.0, or is it too soon to ask?

**Comment by jmvallet** [comment]
Yep, plugin should be compatible with the upcoming v1.2.0.

**Comment by ghost** [comment]
Great, thanks for all your work on this.
