### ISSUE TITLE
wrong translation

### ISSUE THREAD

**Issue by cforce** [Pertimm/redmine_extended_spent_time#5]
The Plural of week in german isn't "Woches" but "Wochen" The method "pluralize" (dunno where that is defined) used in "https://github.com/Pertimm/redmine_extended_spent_time/blob/master/app/views/my/blocks/_log.html.erb" can't ever work, because it would need a complete dictionary for all languages. At least in german there is no standard building for Plural, it depends on the words roots. 
I suggest to add one more lavel for plural of weeks, eg

label_extended_spent_time_weeks: "weeks" ( in german that would be label_extended_spent_time_weeks: "Wochen)" and remove thta error prone "pluralize" usage.

**Comment by jmvallet** [comment]
Fixed: https://github.com/Pertimm/redmine_extended_spent_time/commit/deccd7bd8cf4b6c30624b440f5aeb5fe940fdb67

Thanks.
